name: test 

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      uses: actions/checkout@v3
    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v2.1.0
      with: 
        role-to-assume: arn:aws:iam::512220559759:role/test-gh-actions-isaac
        role-session-name: test-gh-workflow
        aws-region: ${{ env.AWS_REGION }}
    - name: GetCallerId
      run: |
        aws sts get-caller-identity
  
  GoogleAuth:
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'principalSet://iam.googleapis.com/projects/299668006770/locations/global/workloadIdentityPools/github-actions'
        service_account: 'gha-sa@tranquil-racer-388319.iam.gserviceaccount.com'