name: test 

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    strategy:
      matrix:
        foo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      uses: actions/checkout@v3
    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v2.1.0
      with: 
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        role-session-name: test-gh-workflow
        aws-region: ${{ env.AWS_REGION }}
    - name: GetCallerId
      run: |
        aws sts get-caller-identity
  
#  GoogleAuth:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: 'actions/checkout@v3'
#    - id: 'auth'
#      name: 'Authenticate to GCP'
#      uses: 'google-github-actions/auth@v1'
#      with:
#        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}
#        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#    - name: 'setup CloudSDK'
#      uses: 'google-github-actions/setup-gcloud@v1'
#      with:
#        version: '>=363.0.0'
#    - name: 'command'
#      run: |
#        gcloud auth list
#        gcloud compute instances list