name: test 

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      uses: actions/checkout@v3
    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v2.1.0
      with: 
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        role-session-name: test-gh-workflow
        aws-region: ${{ env.AWS_REGION }}
    - name: GetCallerId
      run: |
        aws sts get-caller-identity
  
  GoogleAuth:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}
    - name: 'setup CloudSDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>=363.0.0'
    - name: 'command'
      run: |
        gcloud auth list
        gcloud compute instances list