name: test 

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      uses: actions/checkout@v3
    - name: configure aws creds
      uses: aws-actions/configue-aws-credentials@v2.1.0
      with: 
        role-to-assume: arn:aws:iam::512220559759:role/test-gh-actions-isaac
        role-session-name: test-gh-workflow
        aws-region: ${{ env.AWS_REGION }}
    - name: GetCallerId
      run: |
        aws sts get-caller-identity